#!/bin/sh

# Launching things

killall -9 sxhkd
sxhkd -m 1 &

killall -9 dunst
/usr/bin/dunst &

$HOME/.config/polybar/launch.sh

killall -9 flameshot
flameshot &

# X11 things

# Remap CapsLock to Escape
setxkbmap -option caps:escape

# Set the default cursor (rather than the X shaped one)
xsetroot -cursor_name left_ptr

# Background color
xsetroot -solid '#1d2021'

# bspwm things

bspc monitor -d I II III IV V VI VII VIII IX

bspc config focus_follows_pointer true
bspc config border_width          2
bspc config window_gap            8
bspc config top_padding           44

# bspc config normal_border_color   '#333333'
# bspc config active_border_color   '#333333'
# bspc config focused_border_color  '#333333'
# bspc config presel_feedback_color '#333333'

# active: focused on a non-focused monitor.
# focused: focused on the current monitor.
bspc config normal_border_color "#a89984"
bspc config active_border_color "#a89984"
bspc config focused_border_color "#ebdbb2"
bspc config presel_feedback_color "#ebdbb2"

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false

#  bspwm windows

# reset rules
bspc rule -r *:*

# Use xprop to get the window names
bspc rule -a KeePassXC state=floating center=on rectangle="1200x800+0+0"
bspc rule -a Zathura state=floating center=on rectangle="1200x1076+0+0"
bspc rule -a "Spotify" state=floating center=on rectangle="1200x800+0+0"
# bspc rule -a "Spotify Premium" desktop=V state=tiled
#bspc rule -a Nightly desktop='^2' follow=on
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
